# Site settings
title: Nidal Fikri | Malware RE
description: Hunting Malwares, Securing Cyber Space.
#baseurl: "/TEST" # the subpath of your site, e.g. /blog
#url: "https://github.com/NidalFikri/aboutme/tree/master" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nidal Fikri
user_description: Malware Research Analyst at Triage Sanbbox by Recorded Future. Ex-Trend Micro CPITS intern. Also, I am the author of some fun CTFs at CyberDefenders. Learning how computers are designed & how they function is my ultimate hobby. I can't stop stalking the internals & I love to REVERSE them.
user_title: Malware Analyst at Recorded Future
email: nidalfikrikamil@gmail.com
twitter_username: cyber_anubis
github_username:  cyber-anubis
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
