# Site settings
title: Nidal Fikri
description: Hunting Malwares, Securing Cyber Space.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nidal Fikri
user_description: Malware Analysis RE enthusiast.
Learning how computers are designed & how they function is my ultimate hobby. I can't stop myself from stalking the internals & I love to REVERSE them. Trend Micro CPITS intern. ACM problem solver, competitions player, public speaker & student activity leader.
user_title: Malware Analyst
email: nidalfikrikamil@gmail.com
twitter_username: cyber_anubis
github_username:  NidalFikri
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
